/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package archivos;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author rafa
 */
public class AbrirArch extends javax.swing.JFrame {

    /**
     * Creates new form AbrirArch
     */
    public AbrirArch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPermisos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnOds = new javax.swing.JButton();
        btnOdf = new javax.swing.JButton();
        btnJpg = new javax.swing.JButton();
        btnTxt = new javax.swing.JButton();
        lbOds = new javax.swing.JLabel();
        lbOdf = new javax.swing.JLabel();
        lbJpg = new javax.swing.JLabel();
        lbTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPermisos.setBackground(new java.awt.Color(102, 0, 0));
        btnPermisos.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnPermisos.setForeground(new java.awt.Color(255, 255, 255));
        btnPermisos.setText("Permisos");
        btnPermisos.setBorder(null);
        btnPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermisosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPermisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 100, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(102, 51, 0)));

        btnOds.setBackground(new java.awt.Color(153, 51, 0));
        btnOds.setForeground(new java.awt.Color(255, 255, 255));
        btnOds.setText("Abrir");
        btnOds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdsActionPerformed(evt);
            }
        });

        btnOdf.setBackground(new java.awt.Color(153, 51, 0));
        btnOdf.setForeground(new java.awt.Color(255, 255, 255));
        btnOdf.setText("Abrir");
        btnOdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdfActionPerformed(evt);
            }
        });

        btnJpg.setBackground(new java.awt.Color(153, 51, 0));
        btnJpg.setForeground(new java.awt.Color(255, 255, 255));
        btnJpg.setText("Abrir");
        btnJpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJpgActionPerformed(evt);
            }
        });

        btnTxt.setBackground(new java.awt.Color(153, 51, 0));
        btnTxt.setForeground(new java.awt.Color(255, 255, 255));
        btnTxt.setText("Abrir");
        btnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTxtActionPerformed(evt);
            }
        });

        lbOds.setFont(new java.awt.Font("Likhan", 1, 18)); // NOI18N
        lbOds.setForeground(new java.awt.Color(0, 0, 0));
        lbOds.setText("ods");

        lbOdf.setFont(new java.awt.Font("Likhan", 1, 18)); // NOI18N
        lbOdf.setForeground(new java.awt.Color(0, 0, 0));
        lbOdf.setText("odf");

        lbJpg.setFont(new java.awt.Font("Likhan", 1, 18)); // NOI18N
        lbJpg.setForeground(new java.awt.Color(0, 0, 0));
        lbJpg.setText("jpg");

        lbTxt.setFont(new java.awt.Font("Likhan", 1, 18)); // NOI18N
        lbTxt.setForeground(new java.awt.Color(0, 0, 0));
        lbTxt.setText("txt");
        lbTxt.setToolTipText("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/txt.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jpg.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/odf.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ods.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbTxt))
                    .addComponent(lbJpg)
                    .addComponent(lbOdf)
                    .addComponent(lbOds))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOds)
                    .addComponent(btnOdf)
                    .addComponent(btnJpg)
                    .addComponent(btnTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTxt)
                            .addComponent(btnTxt))
                        .addGap(14, 14, 14)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbJpg)
                            .addComponent(btnJpg)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOdf)
                            .addComponent(btnOdf))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOds)
                            .addComponent(btnOds))
                        .addGap(37, 37, 37))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 450, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoAbrir.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 680, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermisosActionPerformed
        Permisos p = new Permisos();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPermisosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String txt = "texto.txt";
        File fTxt = tipoArchivo(txt);
        String jpg = "imagen.jpg";
        File fJpg = tipoArchivo(jpg);
        String odf = "mate.odf";
        File fOdf = tipoArchivo(odf);
        String ods = "hojaCalculo.ods";
        File fOds = tipoArchivo(ods);

        this.lbTxt.setText(fTxt.getName());
        this.lbJpg.setText(fJpg.getName());
        this.lbOdf.setText(fOdf.getName());
        this.lbOds.setText(fOds.getName());
    }//GEN-LAST:event_formWindowOpened

    private void btnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTxtActionPerformed
        abrir("texto.txt");
    }//GEN-LAST:event_btnTxtActionPerformed

    private void btnJpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJpgActionPerformed
        abrir("imagen.jpg");
    }//GEN-LAST:event_btnJpgActionPerformed

    private void btnOdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdfActionPerformed
        abrir("mate.odf");
    }//GEN-LAST:event_btnOdfActionPerformed

    private void btnOdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdsActionPerformed
        abrir("hojaCalculo.ods");
    }//GEN-LAST:event_btnOdsActionPerformed

    private void abrir(String tipoArchivo) {
        try {
            File archivo = tipoArchivo(tipoArchivo);
            if (archivo.exists()) {
                try {
                    if (!archivo.canExecute()) {
                        JOptionPane.showMessageDialog(null, "No es ejecutable no se puede abrir", "Error", JOptionPane.ERROR_MESSAGE);
                    } else if (!archivo.canRead()) {

                        String botones[] = new String[]{"No", "Si"};
                        int eleccion = JOptionPane.showOptionDialog(this, "No tiene permisos de lectura ¿Desea continuar?", "Permisos", 0, JOptionPane.WARNING_MESSAGE, null, botones, this);
                        if (eleccion == 1) {
                            Desktop.getDesktop().open(archivo);
                        }
                    } else {
                        Desktop.getDesktop().open(archivo);
                    }
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Error al abrir el archivo", "Error", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El archivo no existe", "Error", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            
        }

    }

    private File tipoArchivo(String tipoArch) {
        File f = new File(tipoArch);
        return f;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbrirArch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbrirArch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbrirArch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbrirArch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbrirArch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJpg;
    private javax.swing.JButton btnOdf;
    private javax.swing.JButton btnOds;
    private javax.swing.JButton btnPermisos;
    private javax.swing.JButton btnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbJpg;
    private javax.swing.JLabel lbOdf;
    private javax.swing.JLabel lbOds;
    private javax.swing.JLabel lbTxt;
    // End of variables declaration//GEN-END:variables
}
