/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package archivos;

import cjb.ci.CtrlInterfaz;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafa
 */
public class Permisos extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form Archivos
     */
    public Permisos() {
        initComponents();
        String[] titulo = {"Archivo", "Leer", "Editar", "Ejecutar"};
        dtm.setColumnIdentifiers(titulo);
        tblP.setModel(dtm);
    }

    private void agregarTipo() {
        try {
            cBoxArchivo.addItem("texto.txt");
            cBoxArchivo.addItem("imagen.jpg");
            cBoxArchivo.addItem("mate.odf");
            cBoxArchivo.addItem("hojaCalculo.ods");

            String txt = "texto.txt";
            String jpg = "imagen.jpg";
            String odf = "mate.odf";
            String ods = "hojaCalculo.ods";

            File archTxt = new File(txt);
            int[] permTxt = per(archTxt);

            File archJpg = new File(jpg);
            int[] permJpg = per(archJpg);

            File archOdf = new File(odf);
            int[] permOdf = per(archOdf);

            File archOds = new File(ods);
            int[] permOds = per(archOds);

            dtm.addRow(new Object[]{
                archTxt.getName(), permTxt[0], permTxt[1], permTxt[2]
            });

            dtm.addRow(new Object[]{
                archJpg.getName(), permJpg[0], permJpg[1], permJpg[2]
            });

            dtm.addRow(new Object[]{
                archOdf.getName(), permOdf[0], permOdf[1], permOdf[2]
            });

            dtm.addRow(new Object[]{
                archOds.getName(), permOds[0], permOds[1], permOds[2]
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algún archivo no se encontro, verifique", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private int[] per(File arch) {
        int permisos[] = new int[3];

        permisos[0] = arch.canRead() ? 1 : 0;
        permisos[1] = arch.canWrite() ? 1 : 0;
        permisos[2] = arch.canExecute() ? 1 : 0;

        return permisos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        cBoxArchivo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtLeer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEditar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtExe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblP = new javax.swing.JTable();
        btnPermisos = new javax.swing.JButton();
        btnArchivos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("aakar", 0, 48)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Nakula", 2, 48)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(153, 0, 51));
        lbTitulo.setText("Sistema de Archivos");
        jPanel2.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -10, -1, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 850, 50));

        cBoxArchivo.setEnabled(false);
        jPanel1.add(cBoxArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 137, -1));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Archivo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 102, 0));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setToolTipText("");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        txtLeer.setToolTipText("Escribe 0 o 1");
        txtLeer.setEnabled(false);
        txtLeer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLeerKeyTyped(evt);
            }
        });
        jPanel1.add(txtLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 78, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Leer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        txtEditar.setToolTipText("Escribe 0 o 1");
        txtEditar.setEnabled(false);
        txtEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditarKeyTyped(evt);
            }
        });
        jPanel1.add(txtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 73, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Editar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        txtExe.setToolTipText("Escribe 0 o 1");
        txtExe.setEnabled(false);
        txtExe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExeKeyTyped(evt);
            }
        });
        jPanel1.add(txtExe, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 77, -1));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ejecutar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        tblP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblP.setEnabled(false);
        jScrollPane1.setViewportView(tblP);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, 92));

        btnPermisos.setBackground(new java.awt.Color(0, 102, 0));
        btnPermisos.setForeground(new java.awt.Color(255, 255, 255));
        btnPermisos.setText("Cambiar Permisos");
        btnPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermisosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPermisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        btnArchivos.setBackground(new java.awt.Color(255, 102, 51));
        btnArchivos.setForeground(new java.awt.Color(255, 255, 255));
        btnArchivos.setText("Archivos");
        btnArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivosActionPerformed(evt);
            }
        });
        jPanel1.add(btnArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 104, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoArhivos.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        agregarTipo();
    }//GEN-LAST:event_formWindowOpened

    private void btnPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermisosActionPerformed
        CtrlInterfaz.habilita(true, this.cBoxArchivo);
        CtrlInterfaz.habilita(true, this.txtLeer);
        CtrlInterfaz.habilita(true, this.txtEditar);
        CtrlInterfaz.habilita(true, this.txtExe);
        CtrlInterfaz.habilita(true, this.btnActualizar);
        CtrlInterfaz.habilita(true, this.btnCancelar);

    }//GEN-LAST:event_btnPermisosActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String archivo = this.cBoxArchivo.getSelectedItem().toString();

        if (this.txtLeer.getText().isEmpty() || this.txtEditar.getText().isEmpty()
                || this.txtExe.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!validarNum(this.txtLeer.getText().trim())
                    && !validarNum(this.txtEditar.getText().trim())
                    && !validarNum(this.txtExe.getText().trim())) {

                JOptionPane.showMessageDialog(null, "Formato incorrecto, solo se aceptan 1 o 0", "Error", JOptionPane.ERROR_MESSAGE);

            } else {
                String mensaje = "Permisos actulizados del archivo " + archivo;
                File archTxt = new File(archivo);
                int lectura = Integer.parseInt(this.txtLeer.getText().trim());
                int escritura = Integer.parseInt(this.txtEditar.getText().trim());;
                int ejecutable = Integer.parseInt(this.txtExe.getText().trim());;

                boolean r = lectura == 1 ? archTxt.setReadable(true) : archTxt.setReadable(false);
                boolean w = escritura == 1 ? archTxt.setWritable(true) : archTxt.setWritable(false);
                boolean x = ejecutable == 1 ? archTxt.setExecutable(true) : archTxt.setExecutable(false);

                JOptionPane.showMessageDialog(null, mensaje, "Aviso", JOptionPane.INFORMATION_MESSAGE);

                cancelar();

                this.cBoxArchivo.removeAllItems();
                int rows = this.dtm.getRowCount();
                for (int i = 0; i < rows; i++) {
                    this.dtm.removeRow(0);
                }
                agregarTipo();

            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivosActionPerformed
        AbrirArch a = new AbrirArch();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnArchivosActionPerformed

    private void txtLeerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLeerKeyTyped
        num(evt, this.txtLeer.getText().length());
    }//GEN-LAST:event_txtLeerKeyTyped

    private void txtEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarKeyTyped
        num(evt, this.txtEditar.getText().length());
    }//GEN-LAST:event_txtEditarKeyTyped

    private void txtExeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExeKeyTyped
        num(evt, this.txtExe.getText().length());
    }//GEN-LAST:event_txtExeKeyTyped

    private void num(KeyEvent evt, int longitud) {
        char c = evt.getKeyChar();
        if (c < '0' || c > '1') {
            evt.consume();
        } else if (longitud > 0) {
            evt.consume();
        }
    }

    private static boolean validarNum(String datos) {
        return datos.matches("[0-1]");
    }

    private void cancelar() {
        CtrlInterfaz.limpia(this.txtLeer);
        CtrlInterfaz.limpia(this.txtEditar);
        CtrlInterfaz.limpia(this.txtExe);
        CtrlInterfaz.limpia(this.btnActualizar);

        CtrlInterfaz.habilita(false, this.cBoxArchivo);
        CtrlInterfaz.habilita(false, this.txtLeer);
        CtrlInterfaz.habilita(false, this.txtEditar);
        CtrlInterfaz.habilita(false, this.txtExe);
        CtrlInterfaz.habilita(false, this.btnActualizar);
        CtrlInterfaz.habilita(false, this.btnCancelar);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Permisos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnArchivos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPermisos;
    private javax.swing.JComboBox<String> cBoxArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tblP;
    private javax.swing.JTextField txtEditar;
    private javax.swing.JTextField txtExe;
    private javax.swing.JTextField txtLeer;
    // End of variables declaration//GEN-END:variables
}
